import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sohne = localFont({
  src: "./fonts/TestSohne.otf",
  variable: "--font-sohne",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Test Veronica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sohne.variable}`}>{children}</body>
    </html>
  );
}
